---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/muhamad8/public_html/
    - cd $DEPLOYPATH
    - git fetch origin
    - git reset --hard origin/main
    - composer install --no-dev --optimize-autoloader
    - php artisan config:clear
    - php artisan route:clear
    - php artisan cache:clear
    - php artisan view:clear
